### ISSUE TITLE
Cannot generate migration under Rails 4

### ISSUE THREAD

**Issue by calve** [olkarls/has_permalink#21]
Hi. It looks like the migration generator is broken with Rails 4. Here is my stacktrace

```
$ bin/rails generate has_permalink Products
/usr/lib/ruby/gems/2.2.0/gems/railties-4.1.5/lib/rails/generators/actions/create_migration.rb:13:in `migration_file_name': protected method `migration_file_name' called for #<HasPermalinkGenerator:0x000000049d8ba0> (NoMethodError)
        from /usr/lib/ruby/gems/2.2.0/gems/railties-4.1.5/lib/rails/generators/actions/create_migration.rb:34:in `existing_migration'
        from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:112:in `invoke_with_conflict_check'
        from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
        from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
        from /usr/lib/ruby/gems/2.2.0/gems/railties-4.1.5/lib/rails/generators/migration.rb:34:in `create_migration'
        from /usr/lib/ruby/gems/2.2.0/gems/railties-4.1.5/lib/rails/generators/migration.rb:63:in `migration_template'
        from /home/goudale/.bundler/ruby/2.2.0/has_permalink-732d115169d0/lib/generators/has_permalink_generator.rb:11:in `generate_migration'
        from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/lib/ruby/gems/2.2.0/gems/railties-4.1.5/lib/rails/generators.rb:157:in `invoke'
        from /usr/lib/ruby/gems/2.2.0/gems/railties-4.1.5/lib/rails/commands/generate.rb:11:in `<top (required)>'
        from /usr/lib/ruby/gems/2.2.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
        from /usr/lib/ruby/gems/2.2.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `block in require'
        from /usr/lib/ruby/gems/2.2.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /usr/lib/ruby/gems/2.2.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
        from /usr/lib/ruby/gems/2.2.0/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:135:in `generate_or_destroy'
        from /usr/lib/ruby/gems/2.2.0/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:51:in `generate'
        from /usr/lib/ruby/gems/2.2.0/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /usr/lib/ruby/gems/2.2.0/gems/railties-4.1.5/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

```

Please let me know if you need more informations

**Comment by svennerberg** [comment]
I also have this issue.

**Comment by svennerberg** [comment]
@calve You can get around this issue by creating a migration yourself. Here's how I did it for a model called Article.

```bash
$ rails g migration AddPermalinkToArticles
```
And then edit the migration so it looks like this:

```ruby
class AddPermalinkToArticles < ActiveRecord::Migration
  def self.up
    add_column :articles, :permalink, :string
    add_index :articles, :permalink
  end
  def self.down
    remove_column :articles, :permalink
  end
end
````

Don't forget to add has_permalink to the model. In my case I want to use the title of the article to generate the permalink.

/app/models/article.rb

```ruby
class Article < ActiveRecord::Base
	has_permalink :title
end
```

**Comment by calve** [comment]
I used (friendly id)[https://github.com/norman/friendly_id] instead, but thanks for sharing a solution.

**Comment by olkarls** [comment]
This is now fixed in version 0.1.7. 

Thank you!

**Comment by svennerberg** [comment]
Good Job @olkarls! Still loving has_permalink! :)

**Comment by olkarls** [comment]
Thanks mate :)
